// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgCWh4YwzaXQJSEj0nal3M7fwoOyznLoY',
    appId: '1:300050023025:web:cbc2c716cd2737a7f751d0',
    messagingSenderId: '300050023025',
    projectId: 'examaker-5cf4b',
    authDomain: 'examaker-5cf4b.firebaseapp.com',
    storageBucket: 'examaker-5cf4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Gez1Pi9JTLl9NArfWtHAoQh10OsB3iU',
    appId: '1:300050023025:android:72cdc58dc836f1c4f751d0',
    messagingSenderId: '300050023025',
    projectId: 'examaker-5cf4b',
    storageBucket: 'examaker-5cf4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7LpK0czmTdtTZ6jIbDfiigzn8APMXuKE',
    appId: '1:300050023025:ios:fb8b4c88bb77a6d2f751d0',
    messagingSenderId: '300050023025',
    projectId: 'examaker-5cf4b',
    storageBucket: 'examaker-5cf4b.appspot.com',
    iosClientId: '300050023025-6jjf2ohe77ah58459kh3ltauer5ua5k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.examaker',
  );
}
